runtime: php73 # Replace with php74 to use PHP 7.4
env: flex

beta_settings:
  cloud_sql_insances: cst-323-activity4:us-central1:cst-323-activity4

handlers:
  # Serve a directory as a static resource.
  - url: /styles
    static_dir: styles
  
  - url: /business
    static_dir: business

  - url: /presentation
    static_dir: presentation

  -url: /utility
    static_dir: utility

  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

  # Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto
